-- Phase 4: US-001 — practice_items table + practice_results new columns + enum updates
-- Traces to: DEC-003, DEC-009, DEC-010

-- ============================================================
-- 1. Create practice_items table
-- ============================================================

CREATE TABLE IF NOT EXISTS practice_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES auth.users(id),
    course_id       bigint NOT NULL REFERENCES courses(id),
    concept         text NOT NULL,
    practice_type   text NOT NULL,
    question_text   text NOT NULL,
    correct_answer  text,
    options_json    jsonb,
    explanation     text,
    source_chunk_ids int[],
    difficulty_level double precision,
    generation_model varchar(255),
    times_used      int NOT NULL DEFAULT 0,
    last_used_at    timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- Composite index for lookups by user + course + concept
CREATE INDEX IF NOT EXISTS ix_practice_items_user_course_concept
    ON practice_items (user_id, course_id, concept);

-- ============================================================
-- 2. RLS on practice_items: user_id = auth.uid()
-- ============================================================

ALTER TABLE practice_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "practice_items_select_own"
    ON practice_items FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "practice_items_insert_own"
    ON practice_items FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "practice_items_update_own"
    ON practice_items FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "practice_items_delete_own"
    ON practice_items FOR DELETE
    USING (auth.uid() = user_id);

-- ============================================================
-- 3. Add new columns to practice_results
-- ============================================================

ALTER TABLE practice_results
    ADD COLUMN IF NOT EXISTS score double precision,
    ADD COLUMN IF NOT EXISTS feedback text,
    ADD COLUMN IF NOT EXISTS misconceptions_detected text[];
