-- Phase 7: Test Prep — homework_analyses, test_prep_sessions, test_prep_results
-- US-001: Database schema & migration (mitty-dbd.1)
-- Traces to DEC-006 (UUID sessions), DEC-008 (denormalized user_id), DEC-009 (9 CHECK constraints)

-- =========================================================================
-- 1. homework_analyses
-- =========================================================================

CREATE TABLE IF NOT EXISTS homework_analyses (
    id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    assignment_id   integer NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    course_id       integer NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    page_number     integer NOT NULL,
    analysis_json   jsonb NOT NULL,
    image_tokens    integer CHECK (image_tokens > 0 OR image_tokens IS NULL),
    analyzed_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, assignment_id, page_number)
);

CREATE INDEX IF NOT EXISTS ix_homework_analyses_user_assignment
    ON homework_analyses (user_id, assignment_id);

ALTER TABLE homework_analyses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own homework analyses"
    ON homework_analyses FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own homework analyses"
    ON homework_analyses FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own homework analyses"
    ON homework_analyses FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own homework analyses"
    ON homework_analyses FOR DELETE
    USING (auth.uid() = user_id);

-- =========================================================================
-- 2. test_prep_sessions (DEC-006: UUID PK)
-- =========================================================================

CREATE TABLE IF NOT EXISTS test_prep_sessions (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id       integer NOT NULL REFERENCES courses(id),
    assessment_id   integer REFERENCES assessments(id),
    state_json      jsonb NOT NULL,
    started_at      timestamptz NOT NULL DEFAULT now(),
    completed_at    timestamptz,
    total_problems  integer NOT NULL DEFAULT 0 CHECK (total_problems >= 0),
    total_correct   integer NOT NULL DEFAULT 0 CHECK (total_correct >= 0 AND total_correct <= total_problems),
    duration_seconds integer CHECK (duration_seconds >= 0 OR duration_seconds IS NULL),
    phase_reached   text CHECK (phase_reached IN ('diagnostic', 'focused_practice', 'error_analysis', 'mixed_test', 'calibration')),
    CONSTRAINT chk_completed_after_started CHECK (completed_at IS NULL OR completed_at >= started_at)
);

CREATE INDEX IF NOT EXISTS ix_test_prep_sessions_user_started
    ON test_prep_sessions (user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS ix_test_prep_sessions_course_started
    ON test_prep_sessions (course_id, started_at DESC);
CREATE INDEX IF NOT EXISTS ix_test_prep_sessions_user_incomplete
    ON test_prep_sessions (user_id, completed_at) WHERE completed_at IS NULL;

ALTER TABLE test_prep_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own test prep sessions"
    ON test_prep_sessions FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own test prep sessions"
    ON test_prep_sessions FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own test prep sessions"
    ON test_prep_sessions FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- =========================================================================
-- 3. test_prep_results (DEC-008: denormalized user_id)
-- =========================================================================

CREATE TABLE IF NOT EXISTS test_prep_results (
    id                      bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id                 uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id              uuid NOT NULL REFERENCES test_prep_sessions(id) ON DELETE CASCADE,
    concept                 text NOT NULL,
    problem_json            jsonb NOT NULL,
    student_answer          text,
    is_correct              boolean,
    score                   float CHECK (score >= 0.0 AND score <= 1.0 OR score IS NULL),
    feedback                text,
    hints_used              integer NOT NULL DEFAULT 0 CHECK (hints_used >= 0),
    worked_example_shown    boolean NOT NULL DEFAULT false,
    time_spent_seconds      integer CHECK (time_spent_seconds >= 0 OR time_spent_seconds IS NULL),
    difficulty              float NOT NULL CHECK (difficulty >= 0.0 AND difficulty <= 1.0),
    created_at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_test_prep_results_session_created
    ON test_prep_results (session_id, created_at);
CREATE INDEX IF NOT EXISTS ix_test_prep_results_user_concept_correct
    ON test_prep_results (user_id, concept, is_correct);
CREATE INDEX IF NOT EXISTS ix_test_prep_results_user_created
    ON test_prep_results (user_id, created_at DESC);

ALTER TABLE test_prep_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own test prep results"
    ON test_prep_results FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own test prep results"
    ON test_prep_results FOR INSERT
    WITH CHECK (auth.uid() = user_id);
