-- Phase 5: AI Roles — New tables, RLS policies, FTS index, and escalation indexes
-- US-001: Database migration

-- =========================================================================
-- 1. ai_audit_log
-- =========================================================================

CREATE TABLE IF NOT EXISTS ai_audit_log (
    id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    call_type   text NOT NULL,
    model       text NOT NULL,
    prompt_version int NOT NULL,
    input_tokens   int NOT NULL,
    output_tokens  int NOT NULL,
    cost_usd    numeric(10,8) NOT NULL,
    duration_ms int NOT NULL,
    status      text NOT NULL CHECK (status IN ('success', 'error', 'rate_limited')),
    error_msg   text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_ai_audit_log_user_created
    ON ai_audit_log (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_ai_audit_log_call_type_created
    ON ai_audit_log (call_type, created_at DESC);

ALTER TABLE ai_audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own audit log"
    ON ai_audit_log FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Authenticated users can insert own audit log"
    ON ai_audit_log FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- =========================================================================
-- 2. coach_messages
-- =========================================================================

CREATE TABLE IF NOT EXISTS coach_messages (
    id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    study_block_id  bigint NOT NULL REFERENCES study_blocks(id) ON DELETE CASCADE,
    role            text NOT NULL CHECK (role IN ('student', 'coach')),
    content         text NOT NULL,
    sources_cited   jsonb,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_coach_messages_user_block_created
    ON coach_messages (user_id, study_block_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_coach_messages_block_created
    ON coach_messages (study_block_id, created_at ASC);

ALTER TABLE coach_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own coach messages"
    ON coach_messages FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own coach messages"
    ON coach_messages FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- =========================================================================
-- 3. escalation_log
-- =========================================================================

CREATE TABLE IF NOT EXISTS escalation_log (
    id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    signal_type     text NOT NULL CHECK (signal_type IN ('repeated_failure', 'avoidance', 'confidence_crash')),
    concept         text,
    context_data    jsonb,
    suggested_action text,
    acknowledged    boolean NOT NULL DEFAULT false,
    acknowledged_at timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_escalation_log_user_created
    ON escalation_log (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_escalation_log_signal_created
    ON escalation_log (signal_type, created_at DESC);

ALTER TABLE escalation_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own escalation log"
    ON escalation_log FOR SELECT
    USING (auth.uid() = user_id);

-- =========================================================================
-- 4. flagged_responses
-- =========================================================================

CREATE TABLE IF NOT EXISTS flagged_responses (
    id                bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id           uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    coach_message_id  bigint NOT NULL REFERENCES coach_messages(id) ON DELETE CASCADE,
    reason            text NOT NULL,
    flag_context      jsonb,
    reviewed          boolean NOT NULL DEFAULT false,
    reviewed_at       timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_flagged_responses_user_created
    ON flagged_responses (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_flagged_responses_reviewed_created
    ON flagged_responses (reviewed, created_at DESC);

ALTER TABLE flagged_responses ENABLE ROW LEVEL SECURITY;

-- Admin-only reads (Phase 7); block all SELECT for now
CREATE POLICY "No direct reads on flagged responses"
    ON flagged_responses FOR SELECT
    USING (false);

CREATE POLICY "Authenticated users can insert own flagged responses"
    ON flagged_responses FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- =========================================================================
-- 5. FTS on resource_chunks
-- =========================================================================

ALTER TABLE resource_chunks
    ADD COLUMN IF NOT EXISTS search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(content_text, ''))) STORED;

CREATE INDEX IF NOT EXISTS ix_resource_chunks_search_vector
    ON resource_chunks USING GIN(search_vector);

-- =========================================================================
-- 6. Additional indexes for escalation detection
-- =========================================================================

-- Supports repeated-failure detection queries
CREATE INDEX IF NOT EXISTS ix_practice_results_user_concept_correct
    ON practice_results (user_id, concept, is_correct);

-- Supports avoidance detection (skipped/incomplete blocks per user)
CREATE INDEX IF NOT EXISTS ix_study_blocks_plan_status
    ON study_blocks (plan_id, status);
