-- Phase 6: Block Guides — study_block_guides, block_artifacts, guide_content_cache
-- US-001: Schema migration + SQLAlchemy definitions
-- No RLS policies (DEC-009): app-layer auth only, consistent with study_blocks

-- =========================================================================
-- 1. study_block_guides
-- =========================================================================

CREATE TABLE IF NOT EXISTS study_block_guides (
    id                      bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    block_id                bigint NOT NULL UNIQUE REFERENCES study_blocks(id) ON DELETE CASCADE,
    concepts_json           jsonb,
    source_bundle_json      jsonb,
    steps_json              jsonb,
    warmup_items_json       jsonb,
    exit_items_json         jsonb,
    completion_criteria_json jsonb,
    success_criteria_json   jsonb,
    guide_version           text NOT NULL DEFAULT '1.0',
    generated_at            timestamptz NOT NULL DEFAULT now()
);

-- block_id UNIQUE constraint already creates a unique index (DEC-014)

-- =========================================================================
-- 2. block_artifacts
-- =========================================================================

CREATE TABLE IF NOT EXISTS block_artifacts (
    id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    block_id        bigint NOT NULL REFERENCES study_blocks(id) ON DELETE CASCADE,
    step_number     int NOT NULL,
    artifact_type   text NOT NULL,
    content_json    jsonb,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_block_artifacts_block_id
    ON block_artifacts (block_id);

-- =========================================================================
-- 3. guide_content_cache (DEC-002)
-- =========================================================================

CREATE TABLE IF NOT EXISTS guide_content_cache (
    id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    concept         text NOT NULL,
    source_hash     text NOT NULL,
    content_type    text NOT NULL,
    content_json    jsonb NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (concept, source_hash)
);

-- UNIQUE constraint on (concept, source_hash) already creates a unique index (DEC-014)
